export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #eef9f7 0%, #f7fcfa 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #f5fbfa 0%, #f7fcfa 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #f7fdfc 0%, #f7fcfa 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #f9fefc 0%, #f7fcfa 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f7fcfa 0%, #f7fcfa 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #f6fcf8 0%, #f7fcfa 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #ecf7f4 0%, #f7fcfa 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #eafcf7 0%, #f7fcfa 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' }
];

export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just For You",
        description:
        "Get interview questions and model answers based on your role,experience and specific focus areas-according to your choice"
    },
    { 
        id: "02",
        title: "Learn At Your Own Pace!",
        description:"Expand answers only when you are ready.Dive deeper into any concept instantly with AI-powered detailed answer options"

    },
    {
        
        id: "03",
        title: 'Capture Your Insights!',
        description:"Add personal notes to any questions and pin important ones to the top-making your learning more organized and 10x efficient"

    },
    {
        
        id: "04",
        title: 'Understand the "WHY?" Behind Answers',
        description:
        "Beyond just answers -unlock detailed concept explainations generated by AI,helping you master each and every concept!"
    },
    {
        
        id: "05",
        title: "Save, Organize, and Revisit!",
        description:
        "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparations where you left it off!"
    },
];